POST http://localhost:3000/api/failures
Content-Type: application/json

{
    "message": "Stripe API timeout after 30s",
    "service": "payments"
}

###

GET http://localhost:3000/api/failures

###

GET http://localhost:3000/api/failures/1

###

### Delete user
DELETE http://localhost:3000/api/failures/1